### ISSUE TITLE
Add ability to customize models templates

### ISSUE THREAD

**Issue by mixartemev** [reliese/laravel#119]
It would be very convenient to customize the template itself

**Comment by CristianLlanos** [comment]
What kind of customisation you have in mind? Do you have an example?

**Comment by ParatechX** [comment]
Thanks Cristian for making this package available! It is saving me lots time right now. 

If anyone else stumbles across this in search for template customization, this might help:
The code already includes an option via the config. The Factory.php->prepareTemplate() looks for `*.template.model` as an alternative to the default file. Not sure if it is intentional, or a bug, but the config lookup resolves to searching for `*.*.template.model` so it can be tricky to get it working without knowing that. 

Anyhow, this is what I added at the top of my config/model.php file:

    '*' => [
        '*' => [
            'template' => array( 
                'model' => app_path('CustomLibsPath') . '/resources/stubs/whatever.stub',
            ),
        ],

`whatever.stub` just contains the original content from Coders/Model/model plus any customizations. In my case I just wanted to add a simple line in the comment block. 

Hope that helps anyone trying to customize the template to a limited extend.

**Comment by CristianLlanos** [comment]
Great hack! ;)
