### ISSUE TITLE
Want to include a primary key without auto_increment in the $fillable.

### ISSUE THREAD

**Issue by satoshi-minowa** [reliese/laravel#177]
Hi, I want to include a primary key in the $fillable.
The primary key is not registered in $fillable in such a case.

For example, table difinition is
```sql
CREATE TABLE foo
id int(11) NOT NULL,
value varchar(255)
PRIMARY KEY (id)
```
so generated model is
```php
<?php

/**
 * Created by Reliese Model.
 */

namespace App/Models;

use Reliese\Database\Eloquent\Model;

/**
 * Class Foo
 * 
 * @property int $id
 * @property string $value
 *
 * @package App/Models
 */
class Foo extends Model
{
    protected $table = 'foo';
    public $incrementing = false;

    protected $casts = [
        'id' => 'int'
    ];

    protected $fillable = [
        'value'
    ];
}

```

I want to use it like this
```php
Foo::create(['id' => 1, 'value' =>'abc']);
```

Now, [This code](https://github.com/reliese/laravel/blob/master/src/Coders/Model/Model.php#L1124-L1126) unconditionally excludes the primary key.
Please would you like fix it?

**Comment by CristianLlanos** [comment]
If you are using integer ids it's recommended to enable autoincrementing ids. If you do so, you won't have to pass the id as a parameter for the `create` method.

The reason it is a guarded property is to protect your model ids from [mass assignment](https://en.wikipedia.org/wiki/Mass_assignment_vulnerability). However, if you still want to skip that protection there are a numer of ways you can do it and I think the easiest one for your example might be using the `forceCreate` method instead of `create`.

**Comment by satoshi-minowa** [comment]
@CristianLlanos 
Thank you for answering! 
Your suggestion did what I wanted to do.

**Comment by CristianLlanos** [comment]
Happy to help!
