### ISSUE TITLE
  mkdir(): Invalid path  

### ISSUE THREAD

**Issue by devalexandre** [reliese/laravel#38]
I try use other issues solutions but don't work 

I used
`php artisan vendor:publish --tag=reliese-models `

its work, but when I try use a 

`php artisan code:models   `
display a error

`
  [ErrorException]       
  mkdir(): Invalid path 
`

**Comment by CristianLlanos** [comment]
It might be the configuration cache. Clear the configuration cache `php artisan cache:clear` and run `php artisan code:models`, it should work then.

**Comment by CristianLlanos** [comment]
Look at issue https://github.com/reliese/laravel/issues/24

**Comment by devalexandre** [comment]
php artisan cache:clear  don't  have in lumen

**Comment by medeirosrafael** [comment]
@devalexandre in your bootstrap/app.php:
$app->register(Reliese\Coders\CodersServiceProvider::class);
$app->configure('models');

In your config/models.php:
change: 'path' => app_path('Models') to 'path' => base_path('Models')

**Comment by dgrvedado** [comment]
ErrorException  : mkdir(): Invalid path
This step is not clear to me:
1- Do I have to create 'config / models.php'? my laravel does not have that file (5.8)
2- What do I put inside?
3- Then I have this error
ErrorException  : mkdir(): Invalid path
  at /var/www/html/sat/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:466
    462|         if ($force) {
    463|             return @mkdir($path, $mode, $recursive);
    464|         }
    465| 
  > 466|         return mkdir($path, $mode, $recursive);
.......
I think it's because I do not have the file 'config/models.php'. Some example for this file?

**Comment by gabrielnunez1** [comment]
The file is created with php artisan vendor:publish --tag=reliese-models
